
package form;

import db.Parameter;
import db.ResultSetTableModel;
import db.db_connection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


//class login 
public class Login extends javax.swing.JFrame {

    ResultSet rs;
    db_connection db;
    String username1, password1, hak;

    /** Creates new form Login */
    @SuppressWarnings("static-access")
    public Login() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB,new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
         setUndecorated(true);
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        initComponents();
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btn_login = new usu.widget.ButtonGlass();
        txt_username = new usu.widget.TextBox();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LOGIN.png"))); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 110, 30));

        txt_username.setForeground(java.awt.Color.lightGray);
        txt_username.setText("Username");
        txt_username.setToolTipText("");
        txt_username.setFont(new java.awt.Font("Ubahn", 0, 18)); // NOI18N
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 196, -1));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 196, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back login mg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        rs = db.querySelectAll("Users_data", "Username='" + txt_username.getText() + "' and Password='" + txt_password.getText() + "'");
        try {
            while (rs.next()) {
                username1 = rs.getString("Username");
                password1 = rs.getString("Password");
                hak = rs.getString("Type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (username1 == null && password1 == null) {
            JOptionPane.showMessageDialog(this, "Wrong Password");
        } else {
            if (hak.equals("Admin")) {
                Home h = new Home();
                h.setVisible(true);
                h.setName(txt_username.getText()); 
                this.dispose();
            } else if(hak.equals("Cashier")) {
                Home h = new Home();
                h.setVisible(true);
                this.dispose();
            } else if(hak.equals("Pelanggan")){
                MenuPelanggan m = new MenuPelanggan();
                m.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        btn_loginActionPerformed(evt);
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        if (txt_username.getForeground().equals(Color.LIGHT_GRAY)) {
            txt_username.setForeground(Color.black);
            txt_username.setText("");
        }
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        if (txt_username.getForeground().equals(Color.LIGHT_GRAY)) {
            txt_username.setForeground(Color.black);
            txt_username.setText("");
        }
    }//GEN-LAST:event_txt_usernameKeyTyped

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        btn_loginActionPerformed(evt);
}//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPasswordField txt_password;
    private usu.widget.TextBox txt_username;
    // End of variables declaration//GEN-END:variables
}
